# Generated by Django 4.2.28 on 2026-07-27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItemWorklog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("date", models.DateField()),
                ("duration", models.DecimalField(decimal_places=4, max_digits=12)),
                ("description", models.TextField(blank=True, default="")),
                ("source", models.CharField(choices=[("timer", "Timer"), ("manual", "Manual"), ("import", "Import")], default="manual", max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workitemworklog_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="worklogs", to="db.issue")),
                ("logged_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_item_worklogs", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workitemworklog_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
            ],
            options={
                "db_table": "work_item_worklogs",
                "ordering": ("-date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ActiveTimer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("started_at", models.DateTimeField()),
                ("last_warned_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activetimer_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="active_timers", to="db.issue")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activetimer_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="active_work_item_timers", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
            ],
            options={
                "db_table": "active_work_item_timers",
                "constraints": [models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("user",), name="active_timer_unique_active_user")],
            },
        ),
    ]
