# Generated by Hermes Agent on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0122_time_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workitemworklog",
            name="source",
            field=models.CharField(
                choices=[
                    ("timer", "Timer"),
                    ("manual", "Manual"),
                    ("import", "Import"),
                    ("auto_state", "Auto (State)"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="workitemworklog",
            constraint=models.UniqueConstraint(
                fields=("issue",),
                condition=models.Q(
                    ("source", "auto_state"),
                    ("stopped_at__isnull", True),
                    ("deleted_at__isnull", True),
                ),
                name="worklog_unique_open_auto_state_issue",
            ),
        ),
    ]
