# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.15 on 2026-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0128_remove_issuegitlink_issuegitlink_unique_repo_pr_number_when_pr_and_deleted_at_null_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubappinstallation",
            name="account_avatar_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="repository_selection",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubenabledrepository",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="githubenabledrepository",
            name="default_branch",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="githubenabledrepository",
            name="html_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="githubwebhookdelivery",
            name="installation_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
